
from typing import List
from dataclasses import dataclass, field

from schema import BaseDocument

@dataclass
class RAGLLMResponse:
    """ Represents the response returned by a Retrieval-Augmented Generation (RAG) LLM model.

    Attributes:
        user_query: The original user query string that was input to the model.
        llm_resopnse: Response generated by the language model.
        relevant_docs : The list of documents retrieved from the vector store 
            that were used as context for generating the response.
    """
    user_query: str
    llm_resopnse: str = field(repr=False)
    relevant_docs: List[BaseDocument]=  field(repr=False)